# Generated by Django 3.1.7 on 2023-05-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp_register',
            fields=[
                ('e_name', models.CharField(max_length=100, verbose_name='Employee_Name')),
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Phone_Number')),
                ('e_img', models.ImageField(upload_to='', verbose_name='Employee Image')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('location', models.CharField(choices=[('1', 'Kanhangad'), ('2', 'Kasaragod'), ('3', 'Kenjar'), ('4', 'Bajpe'), ('5', 'Mangalore'), ('6', 'Payyanoor'), ('7', 'Sulliya'), ('8', 'Kannur'), ('9', 'Kozhikode'), ('10', 'Kollam'), ('11', 'Kottayam'), ('12', 'Thiruvanathapuram')], default='1', max_length=20, verbose_name='Location')),
                ('service_name', models.CharField(choices=[('1', 'Plumber'), ('2', 'Painter'), ('3', 'Electrician'), ('4', 'Carpender'), ('5', 'Welder'), ('6', 'TV Technician'), ('7', 'Refrigerator Technician'), ('8', 'Motor Technician'), ('9', 'Coconut Climber'), ('10', 'Gardener')], max_length=30, verbose_name='Trade Name')),
                ('certificate_img', models.ImageField(upload_to='', verbose_name='Trade Certificate')),
                ('on_duty', models.BooleanField(default=True)),
                ('registered', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('u_name', models.CharField(max_length=100, verbose_name='User_Name')),
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Phone_Number')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('location', models.CharField(choices=[('1', 'Kanhangad'), ('2', 'Kasaragod'), ('3', 'Kenjar'), ('4', 'Bajpe'), ('5', 'Mangalore'), ('6', 'Payyanoor'), ('7', 'Sulliya'), ('8', 'Kannur'), ('9', 'Kozhikode'), ('10', 'Kollam'), ('11', 'Kottayam'), ('12', 'Thiruvanathapuram')], default='1', max_length=20, verbose_name='Location')),
                ('registered', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
