# Generated by Django 3.1.7 on 2023-05-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='location',
        ),
    ]
