# Generated by Django 3.1.7 on 2023-05-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20230527_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_register',
            name='location',
            field=models.CharField(choices=[('Kanhangad', 'Kanhangad'), ('Kasaragod', 'Kasaragod'), ('Kenjar', 'Kenjar'), ('Bajpe', 'Bajpe'), ('Mangalore', 'Mangalore'), ('Payyanoor', 'Payyanoor'), ('Sulliya', 'Sulliya'), ('Kannur', 'Kannur'), ('Kozhikode', 'Kozhikode'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Thiruvanathapuram', 'Thiruvanathapuram')], default='1', max_length=20, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='emp_register',
            name='service_name',
            field=models.CharField(choices=[('Plumber', 'Plumber'), ('Painter', 'Painter'), ('Electrician', 'Electrician'), ('Carpender', 'Carpender'), ('Welder', 'Welder'), ('TV Technician', 'TV Technician'), ('Refrigerator Technician', 'Refrigerator Technician'), ('Motor Technician', 'Motor Technician'), ('Coconut Climber', 'Coconut Climber'), ('Gardener', 'Gardener')], max_length=30, verbose_name='Trade Name'),
        ),
    ]
