# Generated by Django 3.1.7 on 2023-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20230529_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_register',
            name='location',
            field=models.CharField(choices=[('0', 'Kanhangad'), ('1', 'Kasaragod'), ('2', 'Kenjar'), ('3', 'Bajpe'), ('4', 'Mangalore'), ('5', 'Payyanoor'), ('6', 'Sulliya'), ('7', 'Kannur'), ('8', 'Kozhikode'), ('9', 'Kollam'), ('10', 'Kottayam'), ('11', 'Thiruvanathapuram')], default='1', max_length=20, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='emp_register',
            name='service_name',
            field=models.CharField(choices=[('0', 'Plumber'), ('1', 'Painter'), ('2', 'Electrician'), ('3', 'Carpender'), ('4', 'Welder'), ('5', 'TV Technician'), ('6', 'Refrigerator Technician'), ('7', 'Motor Technician'), ('8', 'Coconut Climber'), ('9', 'Gardener')], max_length=30, verbose_name='Trade Name'),
        ),
    ]
