# Generated by Django 3.1.7 on 2023-06-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20230529_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_register',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
