# Generated by Django 3.1.7 on 2023-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_emp_register_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_register',
            name='e_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Employee_Name'),
        ),
    ]
