# Generated by Django 3.1.7 on 2023-06-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20230603_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='u_name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='User_Name'),
        ),
    ]
