# Generated by Django 3.1.7 on 2023-06-08 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_auto_20230604_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_register',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_register',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emp_register',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Phone_Number'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Phone_Number'),
        ),
    ]
