# Generated by Django 3.1.7 on 2023-06-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20230608_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_register',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user_register',
            name='id',
        ),
        migrations.AddField(
            model_name='emp_register',
            name='e_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user_register',
            name='u_id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
