# Generated by Django 3.1.7 on 2023-06-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_auto_20230608_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_register',
            old_name='e_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user_register',
            old_name='u_id',
            new_name='id',
        ),
    ]
