# Generated by Django 3.1.7 on 2023-06-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20230608_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_register',
            name='id',
            field=models.DateTimeField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='id',
            field=models.DateTimeField(default=0, primary_key=True, serialize=False),
        ),
    ]
