# Generated by Django 3.1.7 on 2023-06-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_auto_20230608_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_register',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user_register',
            name='id',
        ),
        migrations.AlterField(
            model_name='emp_register',
            name='phone_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Phone_Number'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='phone_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Phone_Number'),
        ),
    ]
