# Generated by Django 3.1.7 on 2023-06-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='Requested',
            new_name='requested',
        ),
    ]
