# Generated by Django 3.1.7 on 2023-06-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_auto_20230608_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_name',
            field=models.CharField(default='o', max_length=30, verbose_name='Trade Name'),
        ),
    ]
