# Generated by Django 3.1.7 on 2023-06-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_services_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
