# Generated by Django 3.1.7 on 2023-06-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_services_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_register',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
