# Generated by Django 3.1.7 on 2023-06-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_emp_register_scheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_register',
            name='scheduled',
        ),
    ]
